"""Main module - wrapper to single source of truth."""
from backend import (
    execute_plan_python,
    execute_plan_shell,
    execute_plan_shadow,
    _delegate_execution,
    _delegate_execution_to_python,
    _delegate_execution_to_shell,
    ensure_control_env,
    RouterOutcome,
    DEFAULT_TIMEOUT,
    ExecutionEngine,
    ExecutionResult,
    ClassificationResult,
    RoutingDecision,
)
__all__ = [
    'execute_plan_python',
    'execute_plan_shell',
    'execute_plan_shadow',
    '_delegate_execution',
    '_delegate_execution_to_python',
    '_delegate_execution_to_shell',
    'ensure_control_env',
    'RouterOutcome',
    'DEFAULT_TIMEOUT',
    'ExecutionEngine',
    'ExecutionResult',
    'ClassificationResult',
    'RoutingDecision',
]
